source 'https://rubygems.org'

# Specify your gem's dependencies in sfctl.gemspec
gemspec

gem 'faraday'
gem 'pastel'
gem 'rake', '~> 12.0'
gem 'thor'
gem 'tty-box'
gem 'tty-color'
gem 'tty-command'
gem 'tty-config'
gem 'tty-cursor'
gem 'tty-editor'
gem 'tty-file'
gem 'tty-font'
gem 'tty-link'
gem 'tty-logger'
gem 'tty-markdown'
gem 'tty-pager'
gem 'tty-pie'
gem 'tty-platform'
gem 'tty-progressbar'
gem 'tty-prompt'
gem 'tty-reader'
gem 'tty-screen'
gem 'tty-spinner'
gem 'tty-table'
gem 'tty-tree'
gem 'tty-which'

group :development, :test do
  gem 'fuubar'
  gem 'pry-byebug'
  gem 'rspec'
  gem 'rubocop'
  gem 'simplecov'
  gem 'webmock'
end
