RSpec.describe "'sfctl time providers' command", type: :cli do
  it "executes 'sfctl time providers' command successfully" do
    expected_output = <<~HEREDOC
      Commands:
        sfctl connections add                # This command will add a connection b...
        sfctl connections get                # List all known connections in that p...
        sfctl connections help [COMMAND]     # Describe subcommands or one specific...
        sfctl providers get                  # Read which providers are configured ...
        sfctl providers help [COMMAND]       # Describe subcommands or one specific...
        sfctl providers set                  # Set the configuration required for t...
        sfctl providers unset                # Unset the configuration of a provider.
        sfctl time connections [SUBCOMMAND]  # Manage connections.
        sfctl time help [COMMAND]            # Describe subcommands or one specific...
        sfctl time init                      # You can use the following command to...
        sfctl time providers [SUBCOMMAND]    # Manage providers.

    HEREDOC

    output = `sfctl time --no-color`
    expect(output).to eq expected_output
  end
end
